### ISSUE TITLE
Update Package Dependencies

### ISSUE THREAD

**Issue by dansiegel** [Clancey/Comet#149]
There are actually a couple of issues out of the box with the dependencies on the current release 0.1.7606-beta.

> WARNING: NU1603: Clancey.Comet 0.1.7606-beta depends on Clancey.Comet.Reload (>= 0.0.6-alpha) but Clancey.Comet.Reload 0.0.6-alpha was not found. An approximate best match of Clancey.Comet.Reload 0.0.7-alpha was resolved.

I assume 0.0.6 is on some private CI feed, but either way not the best experience to be referencing a package not on NuGet.org from a package on NuGet.org... also the package probably should just reference 0.0.9-alpha which is the latest build anyway.

> Error | CS0012 | The type 'AppCompatActivity' is defined in an assembly that is not referenced. You must add a reference to assembly 'Xamarin.Android.Support.v7.AppCompat, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'. 

The issue here is that the [NuSpec](https://github.com/Clancey/Comet/blob/dev/Comet.nuspec#L25-L28) is only referencing Xamarin.Essentials and FFImageLoading, while the actual [project](https://github.com/Clancey/Comet/blob/dev/src/Comet.Android/Comet.Android.csproj#L113-L123) relies on a couple of Android Support Libraries. This will quickly lead you to the sort of compile time error I mentioned unless you explicitly go and install the required NuGets.

**Comment by Clancey** [comment]
This is caused by  something odd.. If you add The nuget `Microsoft.VisualStudio.Threading` Manually to the project it will build But it is referenced in the nuspec... https://github.com/Clancey/Comet/blob/dev/Comet.nuspec#L20 . And yes Android needs some more nugets.

**Comment by dansiegel** [comment]
@Clancey so the issue with Microsoft.VisualStudio.Threading is that you actually only have it as a NuGet dependency for unsupported framework targets which NuGet will interpret as anything not iOS, Android or Mac based on the current configuration... technically Clancey.Comet.Reload isn't a dependency for iOS/Mac/Android either (according to NuGet)

**Comment by dansiegel** [comment]
I can confirm btw that adding `Microsoft.VisualStudio.Threading` resolved the issue we discussed with the iOS app building.

**Comment by Clancey** [comment]
[Fixed](https://github.com/Clancey/Comet/commit/e2f1342445d4ec8f17531b139e447c7c1d597747) You can install dev builds from here: https://github.com/Clancey/Comet/packages
