### ISSUE TITLE
"Getting Started" Wiki is incorrect

### ISSUE THREAD

**Issue by saamerm** [Clancey/Comet#173]
The "[Getting Started](https://github.com/Clancey/Comet/wiki/Getting-Started)" wiki states that to start a new project you have to run this command:

`dotnet new comet-app -n RideTheComet`

That is incorrect. "comet-app" is not a template available. The right command is:

`dotnet new comet -n RideTheComet`

I am not able make changes to it, or submit a pull request since it is a Wiki item which doesn't come from a README file from the repo. Please make this small fix so that other developers don't face issues while getting started.

Keep up the great work btw

**Comment by Clancey** [comment]
Thanks, Fixed
