### ISSUE TITLE
Add Styles

### ISSUE THREAD

**Issue by Clancey** [Clancey/Comet#18]
Right now you can set a global FontSize, but you can't do `Label.FontSize`, and `Button.FontSize`.  We also may need style id, and let people set things like `StyleId.Label.FontSize` or `StyleId.FontSize`

**Comment by SuavePirate** [comment]
What are your thoughts on an html/css style relationship with universal `Style` object and properties on `Views`. Could be interesting for allowing custom handlers to implement certain styles types on views where you might not expect them rather than putting individual style properties on each view.

For example, a `CornerRadius` or `BorderRadius` might not make sense for default `Label`, but if I wanted to implement a handler for it, I could on my own. Then you could also implement style classes with strongly typed classes. Here's a dumb and simplified example of what I'm getting at:

```csharp
class Style 
{
    public virtual string Color { get; set; }
    public virtual string BackgroundColor { get; set; }
    public virtual float LetterSpacing { get; set; }
    // and like tons more properties
}

class H1Style : Style
{
    public H1Style()
    {
        Color = "#000000";
    }
}

class View
{
    public Style Style { get; set; }
}


// ...
var myStack = new HStack { new Label { Style = new H1Style() } };
```

**Comment by Clancey** [comment]
@SuavePirate I am looking into Style stuff. I was thinking more StyleID driven. So you would set the styles up once. https://github.com/Clancey/Comet/tree/material-design  I haven't started on H1 type things yet. That is coming. But going this route, it should be nicer since we can do global styles. And have Style.Apply()

**Comment by SuavePirate** [comment]
Love it. I suppose you could pretty easily implement H1 type things by just subclassing components with a default StyleID as well. Let me know how I can help!

**Comment by Clancey** [comment]
So here is a current screen shot created from the following code:
```cs
 public class TextStylesSample : View
    {
        [Body]
        View body() => new VStack
        {
            new Text("H1").StyleAsH1(),
            new Text("H2").StyleAsH2(),
            new Text("H3").StyleAsH3(),
            new Text("H4").StyleAsH4(),
            new Text("H5").StyleAsH5(),
            new Text("H6").StyleAsH6(),
            new Text("Subtitle 1").StyleAsSubtitle1(),
            new Text("Subtitle 2").StyleAsSubtitle2(),
            new Text("Body 1").StyleAsBody1(),
            new Text("Body 2").StyleAsBody2(),
            new Text("Caption").StyleAsBody2(),
            new Text("OVERLINE").StyleAsOverline(),
        };
    }
```
 

![image](https://user-images.githubusercontent.com/256046/67253733-c35b0400-f425-11e9-8808-7d86752aac5d.png)

Added with this [Commit](https://github.com/Clancey/Comet/commit/ad05f6ef2605b910dd72861eba6748e28b91eb6b)

**Comment by SuavePirate** [comment]
Are they applied as extension methods? What does creating your own one-off `StyleAs` methods look like? Love the fluent setup though

**Comment by Clancey** [comment]
Done for most basic controls, I will keep going on the rest of them!
